# Generated by Django 6.0.1 on 2026-01-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bem',
            name='eh_doacao',
        ),
        migrations.AddField(
            model_name='bem',
            name='origem',
            field=models.CharField(choices=[('PROPRIO', 'Próprio'), ('DOACAO', 'Doação'), ('ALUGADO', 'Alugado')], default='PROPRIO', max_length=20),
        ),
    ]
