# Generated by Django 5.2.9 on 2026-01-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gestor_pode_cadastrar_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='criado_em',
        ),
    ]
