# Generated by Django 6.0.1 on 2026-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
