# Generated by Django 5.2.9 on 2026-01-26 00:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_venda_itemvenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Qtd. Estoque'),
        ),
        migrations.AddField(
            model_name='venda',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bem',
            name='estado_conservacao',
            field=models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('REGULAR', 'Regular')], default='EXCELENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bem',
            name='origem',
            field=models.CharField(choices=[('PROPRIO', 'Próprio'), ('CONSIGNADO', 'Consignado')], default='PROPRIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='bem',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala', verbose_name='Seção/Local'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='situacao',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('SEMINOVO', 'Seminovo / Usado'), ('SALDO', 'Saldo / Outlet'), ('DEFEITO', 'Com Defeito / Avaria')], default='NOVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='bem',
            name='tombo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Barras / SKU'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='pode_cadastrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='pode_cadastrar_categoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='pode_cadastrar_gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='pode_cadastrar_sala',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='pode_cadastrar_unidade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='pode_dar_baixa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='pode_editar',
            field=models.BooleanField(default=False),
        ),
    ]
