# Generated by Django 5.2.9 on 2026-01-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bem_quantidade_venda_criado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='situacao',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('SEMINOVO', 'Seminovo / Usado'), ('SALDO', 'Saldo / Outlet'), ('DEFEITO', 'Com Defeito / Avaria'), ('RECUPERAVEL', 'Recuperável')], default='NOVO', max_length=20),
        ),
    ]
