# Generated by Django 5.2.9 on 2026-01-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_bem_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='margem_lucro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Margem (%)'),
        ),
        migrations.AddField(
            model_name='bem',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço de Custo'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço de Venda'),
        ),
    ]
