# Generated by Django 5.2.9 on 2026-01-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bem_margem_lucro_bem_preco_custo_alter_bem_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito'), ('PIX', 'Pix'), ('MUMBUCA', 'Mumbuca')], default='DINHEIRO', max_length=20),
        ),
    ]
