# Generated by Django 5.2.9 on 2026-01-28 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_venda_forma_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='historico',
            options={},
        ),
        migrations.RemoveField(
            model_name='bem',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='data_baixa',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='margem_lucro',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='obs_baixa',
        ),
        migrations.RemoveField(
            model_name='bem',
            name='preco_custo',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='pode_cadastrar',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='pode_cadastrar_categoria',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='pode_cadastrar_gestor',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='pode_cadastrar_sala',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='pode_cadastrar_unidade',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='pode_dar_baixa',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='pode_editar',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='bem',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bem',
            name='data_aquisicao',
            field=models.DateField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bem',
            name='skip_signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='estado_conservacao',
            field=models.CharField(blank=True, default='Excelente', max_length=50),
        ),
        migrations.AlterField(
            model_name='bem',
            name='origem',
            field=models.CharField(blank=True, default='Compra', max_length=100),
        ),
        migrations.AlterField(
            model_name='bem',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bem',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala'),
        ),
        migrations.AlterField(
            model_name='bem',
            name='situacao',
            field=models.CharField(blank=True, default='Novo', max_length=50),
        ),
        migrations.AlterField(
            model_name='bem',
            name='tombo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bem',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gestor',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historico',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sala',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(default='DINHEIRO', max_length=50),
        ),
        migrations.AddField(
            model_name='bem',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.fornecedor'),
        ),
    ]
