# Generated by Django 5.2.9 on 2026-01-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fornecedor_alter_historico_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
