# Generated by Django 5.2.9 on 2026-01-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bem_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('FIXA', 'Despesa Fixa (Luz, Água, Aluguel)'), ('BOLETO', 'Boleto Fornecedor'), ('OUTRO', 'Outros Gastos')], default='FIXA', max_length=20)),
                ('situacao', models.CharField(choices=[('PENDENTE', 'Pendente (A Pagar)'), ('PAGO', 'Pago'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=20)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
            ],
        ),
    ]
