# Generated by Django 5.2.9 on 2026-01-31 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
