# Generated by Django 5.2.9 on 2026-02-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_despesa_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente Geral'), ('vendedor', 'Vendedor'), ('estoque', 'Estoquista')], default='vendedor', max_length=20),
        ),
    ]
