# Generated by Django 5.2.9 on 2026-02-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_gestor_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='estoque_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
