# Generated by Django 5.2.9 on 2026-02-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_bem_estoque_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bem',
            name='estoque_minimo',
            field=models.IntegerField(default=2),
        ),
    ]
