# Generated by Django 5.2.9 on 2026-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_venda_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cliente_solicitou_cupom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='cpf_cnpj_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('MERCADORIA', 'Fornecedor / Mercadoria'), ('AGUA', 'Conta de Água'), ('LUZ', 'Conta de Luz / Energia'), ('INTERNET', 'Internet / Telefone'), ('ALUGUEL', 'Aluguel'), ('FUNCIONARIOS', 'Salários / Funcionários'), ('MANUTENCAO', 'Manutenção / Reparos'), ('IMPOSTOS', 'Impostos / Taxas'), ('FIXA', 'Outras Despesas Fixas'), ('OUTRO', 'Outros Gastos')], default='FIXA', max_length=20),
        ),
    ]
