# Generated by Django 5.2.9 on 2026-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_venda_cliente_solicitou_cupom_venda_cpf_cnpj_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='telefone_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
