# Generated by Django 5.2.9 on 2026-02-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
