# Generated by Django 6.0.1 on 2026-01-19 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tombo', models.CharField(max_length=20, unique=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('situacao', models.CharField(choices=[('RECUPERAVEL', 'Recuperável'), ('ANTIECONOMICO', 'Antieconômico'), ('IRRECUPERAVEL', 'Irrecuperável'), ('OCIOSO', 'Ocioso')], default='RECUPERAVEL', max_length=20)),
                ('estado_conservacao', models.CharField(choices=[('EXCELENTE', 'Excelente - Nota 10'), ('BOM', 'Bom - Nota 8'), ('REGULAR', 'Regular - Nota 5')], default='EXCELENTE', max_length=20)),
                ('eh_doacao', models.BooleanField(default=False, verbose_name='É Doação?')),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('obs_baixa', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidade')),
            ],
        ),
    ]
