# Generated by Django 6.0.1 on 2026-01-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='pode_cadastrar',
            field=models.BooleanField(default=False, verbose_name='Pode Cadastrar Bens?'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='pode_dar_baixa',
            field=models.BooleanField(default=False, verbose_name='Pode dar Baixa?'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='pode_editar',
            field=models.BooleanField(default=False, verbose_name='Pode Editar Bens?'),
        ),
    ]
