# Generated by Django 5.2.9 on 2026-01-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gestor_pode_cadastrar_gestor_pode_dar_baixa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unidade')),
            ],
        ),
    ]
