# Generated by Django 5.2.9 on 2026-01-19 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gestor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='pode_cadastrar_categoria',
            field=models.BooleanField(default=False, verbose_name='Pode Cadastrar Categorias?'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='pode_cadastrar_gestor',
            field=models.BooleanField(default=False, verbose_name='Pode Cadastrar Gestores?'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='pode_cadastrar_sala',
            field=models.BooleanField(default=False, verbose_name='Pode Cadastrar Salas?'),
        ),
        migrations.AddField(
            model_name='gestor',
            name='pode_cadastrar_unidade',
            field=models.BooleanField(default=False, verbose_name='Pode Cadastrar Unidades?'),
        ),
    ]
