# Generated by Django 5.2.9 on 2026-01-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sala_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='bem',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sala', verbose_name='Sala'),
        ),
    ]
